### ISSUE TITLE
installation error argument use

### ISSUE THREAD

**Issue by kemars** [pgmikhael/protgps#4]
Hello,

I Tried to install your software. I followed all your instruction to install and launch the training. but I get error regarding the conflict argument management. 

How can i fix it ?

Best regards,
Marc 

error: 
Traceback (most recent call last):
  File "scripts/main.py", line 116, in <module>
    args = parse_args()
  File "/home/gueroult/src/protgps/protgps/utils/parsing.py", line 566, in parse_args
    parser = Trainer.add_argparse_args(get_parser())
  File "/home/gueroult/src/protgps/protgps/utils/parsing.py", line 559, in get_parser
    add_class_args(vars(global_namespace), parser)
  File "/home/gueroult/src/protgps/protgps/utils/parsing.py", line 553, in add_class_args
    args_for_protgpss[argname].add_args(parser, argval)
  File "/home/gueroult/src/protgps/protgps/utils/classes.py", line 109, in add_args
    get_object(values, object_name).add_args(parser)
  File "/home/gueroult/src/protgps/protgps/datasets/protein_compartments.py", line 299, in add_args
    parser.add_argument(
  File "/home/gueroult/miniconda3/envs/protgps/lib/python3.8/argparse.py", line 1386, in add_argument
    return self._add_action(action)
  File "/home/gueroult/miniconda3/envs/protgps/lib/python3.8/argparse.py", line 1749, in _add_action
    self._optionals._add_action(action)
  File "/home/gueroult/miniconda3/envs/protgps/lib/python3.8/argparse.py", line 1590, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/home/gueroult/miniconda3/envs/protgps/lib/python3.8/argparse.py", line 1400, in _add_action
    self._check_conflict(action)
  File "/home/gueroult/miniconda3/envs/protgps/lib/python3.8/argparse.py", line 1539, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/home/gueroult/miniconda3/envs/protgps/lib/python3.8/argparse.py", line 1548, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --max_prot_len: conflicting option string: --max_prot_len

**Comment by pgmikhael** [comment]
Hi,

Yes, thanks for catching this! The args should now be fixed with an update to the code, and this conflict should be resolved.

**Comment by yoavhadas** [comment]
Thanks for fixing it @pgmikhael . Can you please explain where to find the fix and how to fix the environment?

**Comment by yoavhadas** [comment]
Thanks

**Comment by kemars** [comment]
Thanks to answer so quickly, 
It seems also you forgot to add transformers python library, to your environment file (.yml).
This library is need to install DR-BERT model.

Marc

**Comment by pgmikhael** [comment]
Hi,

Thanks for the comment! We linked to the GitHub of the DR-BERT model in the README instead (in keeping with exact process we used to install). We will update the requirements as well.
